### ISSUE TITLE
Create name and multisend commands

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-chat#22]
# Introduction

As part of our interaction with bounties and games, we need ways to make sending messages easier. First, we need to provide users with ways to "remember" names rather than long address, and second, be able to send multiple messages at once as to speed up interaction and avoiding them having to do "send X", "send X" all the time. These two new commands are called `name` and `multisend`. Here's an example of the workflow:

**name**
```
>name $ADDRESS $ALIAS
>name 16Uiu2HAmKNt8DRL47QYPikG7fpZPpLAdWWC8JGDPLCBELfD2cu9g chatbot
>send chatbot
```

**multisend***
```
>multisend $ADDRESS|$ALIAS
hi there
all good
ok, see ya
quit
>
```

For `name`, the storage will be inmemory for the time being, so restarting the chat app would sadly remove existing aliases. We might find other options later on to restore these aliases. For `multisend`, every enter sends a message, and typing `quit` or sending an interruption signal would return users to the command section.

# Task Description
- [ ] Create `name` and test it
- [ ] Create `multisend` and test it

# Definition of complete
The task is considered completed when both commands are up and running, working locally, and can be embedded in our binary (running `yarn:compile` will help you see if that's the case).

# Testing criteria
- [ ] You can speak to our twitter bot `16Uiu2HAmQDFS8a4Bj5PGaTqQLME5SZTRNikz9nUPT3G4T6YL9o7V` by aliasing it as `name 16Uiu2HAmQDFS8a4Bj5PGaTqQLME5SZTRNikz9nUPT3G4T6YL9o7V twitterbot`
- [ ] You can send multiple messages to our twitter bot and see its responses within the terminal by using `multisend`, without having to do `send` multiple times.
